### ISSUE TITLE
mount of /tmp different in start than in ingest on MacOS (workaround provided)

### ISSUE THREAD

**Issue by alecw** [higlass/higlass-manage#64]
I'm not experienced with Docker, so perhaps I'm doing something dumb, but when trying to `higlass-manage view` a file, the file is linked to the local directory that is supposed to be mounted to /tmp in the docker image, but when trying to tell the image to ingest the file, the file isn't found.  The problem appears to be that when getting the docker configuration with `client.api.inspect_container(container_name)`, it returns the following (just showing the /tmp mount):
```
{'Type': 'bind', 'Source': '/host_mnt/private/tmp/higlass-docker', 'Destination': '/tmp', 'Mode': 'rw', 'RW': True, 'Propagation': 'rprivate'}
```
However, this is not the mapping that was set up by `higlass-manage start`.  There, the default mapping is `    temp_dir="/tmp/higlass-docker"`.

Work-around is to symlink: `cd /tmp; ln -s /host_mnt/private/tmp/higlass-docker .`

Note also that because one can't create directories in / on MacOS Catalina, I needed to use synthetic.conf to make /host_mnt a symlink to a directory in my user directory.

**Comment by pkerpedjiev** [comment]
Thanks for the workaround! Does that get you running for now?

I encountered a similar issue when using `higlass-manage view` but wasn't able to come up with a quick solution. Will have to spend some more time digging this weekend.

**Comment by alecw** [comment]
Yes, I can view my .mcool file now.  I'm still struggling with the UI a bit, but probably that's just because I'm a novice.

**Comment by pkerpedjiev** [comment]
They @alecw thanks a ton for the detailed PR! I searched around a bit and it looks like this is a Docker issues. It should be fixed in a subsequent version but for now there's a setting you can toggle in Docker's preferences to fix it.

https://github.com/docker/for-mac/issues/4859

By the way, if you're having troubles with the UI, feel free to pop into our Slack channel and ask any questions you may have: https://rb.gy/q9do1b
